# Generated by Django 4.0.2 on 2022-02-19 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brandingmodel_productmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='shop.brandingmodel', verbose_name='brand'),
        ),
    ]
