# Generated by Django 4.0.2 on 2022-02-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_productmodel_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandingModel',
        ),
    ]
