# Generated by Django 4.0.2 on 2022-02-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_brandingmodel_productmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='BrandingModel',
        ),
    ]
